version: '3.8'
services:
  #main-service:
  #  container_name: main-service
  #  build: ./main-service
   # ports:
  #    - "8080:8080"
   # depends_on:
 #     - stat-service
 #   environment:
  #    - STATS_SERVICE#_URL=http://stats-server:9090

  stat-service:
    build: stat-service/stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=statistic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - DB_HOST=db
      - DB_PORT=5432

  stats-db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
