server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:h2:file:./db/statistic
    username: test
    password: test
    driverClassName: org.h2.Driver

      #driverClassName: org.postgresql.Driver
      #  url: jdbc:postgresql://localhost:5432/statistic
    # username: postgres
    # password: admin